In [1]:
import pandas as pd
import numpy as np
import random
import os
import datetime
import string

In [2]:
# import data
data = pd.read_csv("/home/bluepi/Downloads/Update/product_info/main table/product_info.csv")
new_product = pd.read_csv("/home/bluepi/Downloads/Update/product_info/main table/new_added.csv")

## Creating date named directory

In [3]:
# Get the current date
current_date = datetime.datetime.today()

# datetime.timedelta(days=1) ---> in order to get the previous date
# strftime ('%d-%m-%Y')  ---> To get the date in time desired format
date_folder = (current_date - datetime.timedelta(days=1)).strftime ('%d-%m-%Y')

# Parent Directory path 
parent_dir = "/home/bluepi/Downloads/Update/product_info"
# os.path.join --> join one or more path components
path = os.path.join(parent_dir, date_folder) 
# Creating Directory
os.mkdir(path)

## Creating CSV file

In [4]:
value = random.randint(1,10)

#data_random_subset
data_random_subset = data.sample(n=value)

# Create the file name as it would be random
file_name = str(''.join(random.choices(string.ascii_uppercase + string.digits, k = 10) ))

# File path
path_csv = path + '/' + file_name + '.csv'

## Updating Data
- Removing day and time
- Adding new prices
- Adding new date_timestamp
- Adding record type -- UPDATED

In [5]:
# Drop the existing price column
data_random_subset = data_random_subset.drop(['price','day','time'],axis=1)

# Add new price column with new prices
data_random_subset['price'] = np.random.randint(1, 1500, size=data_random_subset.shape[0])

# To create date_timestamp
# here we used list comprehensions
# datetime.datetime.today() ---> get the today's date
# datetime.timedelta(minutes= ...,seconds=...) ---> used for calculating differences in dates & date manipulations
data_random_subset['Date_timestamp'] = [(datetime.datetime.today() 
                                  + datetime.timedelta(minutes= random.randint(10,100),
                                                seconds=random.randint(10,100) )).strftime("%d/%m/%Y %H:%M:%S") 
                                     for i in range(data_random_subset.shape[0])] 

# Adding record type data
data_random_subset['record_type'] = 'U'

### Adding new Products

In [6]:
value_2 = random.randint(0,5)

#new products picked at random
new_data_random_subset = new_product.sample(n=value_2)

# Updating new product file
new_product[ ~new_product['p_id'].isin(new_data_random_subset['p_id'].values) ]

    p_id       p_name  price
0    417       Vagram    782
1    856      Konklab    677
2    309     Bytecard    918
3    569    Daltfresh    115
4    127      Andalax    479
5    246      Veribet   1038
6    919         Viva    577
8    831    Holdlamis   1109
9    558     Domainer    835
10   279  Solarbreeze   1368
11   416      Konklab     48
12   764      Fixflex    446
13   404     Domainer   1173
14   119         Span   1207
15   662       Sub-Ex    969
16   335         Rank    165
17   129      Fintone    133
18   929       Latlux     68
19   576       Zoolab    742
20   493       Namfix   1061
21   676        Opela    796
22   276        Opela    780
23   557     Overhold     73
24   949  Toughjoyfax   1204
25   157         Span   1217
26   443        Opela   1343
27   603       Tresom    865
29   293         Rank    965
30   911      Pannier   1057
31   767       Duobam    582
32   369       Lotlux    886
33   154      Redhold     62
34   249     Aerified    265
35   980       Lotlux    618
36   352        Asoka    640
37   967     Treeflex    439
38   409     Alphazap    151
39   985         Span   1375
40   365    Cardguard    896
41   766  Mat Lam Tam   1305
42   745      Fintone    358
43   930          Tin   1150
44   117     Domainer    935
45   675       Tresom   1368
46   725      Sonsing    640
47   923  Stringtough   1366
48   462       Lotlux    943

- Adding the date timestamp
- Adding record type INSERTED

In [7]:
# Adding the date timestamp
new_data_random_subset['Date_timestamp'] = [(datetime.datetime.today() 
                                  + datetime.timedelta(minutes= random.randint(10,100),
                                                seconds=random.randint(10,100) )).strftime("%d/%m/%Y %H:%M:%S") 
                                     for i in range(new_data_random_subset.shape[0])] 

# Adding the record type
new_data_random_subset['record_type'] = 'I'

# Concating newly added and updated products
final_day_update = pd.concat([data_random_subset,new_data_random_subset],sort = False)

In [8]:
# Exporting the csv file
final_day_update.to_csv(path_csv)

## Delete products

In [9]:
# Products which have been deleted
deleted_product = []

# Getting list of all products present in main product table
data_pid = data['p_id'].tolist()

for j in range(10):
    to_delete = random.choices( data_pid, k = random.randint(0,4) )
    print(" to be deleted --> ");print(to_delete)
    print( "All deleted products " , end= '\n') 
    print( deleted_product,end='\n')
    print(" ",end='\n')
    for i in to_delete :
        if i in deleted_product :
            print("to be removed -- >");print(i)
            to_delete.remove(i)
            print("after removing already deleted p-ID",end='\n')
            print(to_delete)
            print(" ",end = '\n')
        else :
            deleted_product.append(i)

 to be deleted -->
[542]
All deleted products
[]

 to be deleted -->
[703, 923]
All deleted products
[542]

 to be deleted -->
[395, 535]
All deleted products
[542, 703, 923]

 to be deleted -->
[]
All deleted products
[542, 703, 923, 395, 535]

 to be deleted -->
[]
All deleted products
[542, 703, 923, 395, 535]

 to be deleted -->
[416, 525]
All deleted products
[542, 703, 923, 395, 535]

 to be deleted -->
[649, 852, 703, 123]
All deleted products
[542, 703, 923, 395, 535, 416, 525]

to be removed -- >
703
after removing already deleted p-ID
[649, 852, 123]

 to be deleted -->
[561, 862, 524, 158]
All deleted products
[542, 703, 923, 395, 535, 416, 525, 649, 852]

 to be deleted -->
[495]
All deleted products
[542, 703, 923, 395, 535, 416, 525, 649, 852, 561, 862, 524, 158]

 to be deleted -->
[308, 673, 395]
All deleted products
[542, 703, 923, 395, 535, 416, 525, 649, 852, 561, 862, 524, 158, 495]

to be removed -- >
395
after removing already deleted p-ID
[308, 673]